// Anthropic API integration for the schedule-review feature (and the shared
// Messages-call plumbing the editor uses).
//
// Sync HTTP via ureq. Tauri 2 runs plain (non-async) commands on the MAIN
// thread, so every command that reaches this code is declared
// `#[tauri::command(async)]` in commands.rs — that moves it onto the async
// runtime's thread pool, where a blocking call can't freeze the UI.
//
// Prompt caching: a prefix only caches above the model's minimum cacheable
// length (512 tokens on Opus/Sonnet 5.5, 4096 on Haiku 4.5), so each caller
// says per system block whether to mark it. The short review prompt is sent
// uncached; the editor prompt and the code-draft script are cached.

use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

const ANTHROPIC_URL: &str = "https://api.anthropic.com/v1/messages";
const ANTHROPIC_VERSION: &str = "2023-06-01";
/// Server-side refusal fallback (Opus/Sonnet 5.5): on a safety-classifier
/// decline the API re-runs the request on a fallback model it picks.
const FALLBACK_BETA: &str = "server-side-fallback-2026-07-01";

/// Output budget for review calls. Opus/Sonnet 5.5 think adaptively and
/// thinking counts against max_tokens, so leave headroom; ~16k keeps a
/// non-streaming request inside a sane HTTP timeout.
const MAX_TOKENS: u32 = 16_000;
const REVIEW_TIMEOUT: Duration = Duration::from_secs(300);

/// List pricing per model (USD per 1M tokens): (input, output, cache_write,
/// cache_read). Cache-write is +25% of input (5-minute TTL). Unknown models
/// price as the older, pricier Opus line so costs are never understated.
pub fn model_prices(model: &str) -> (f64, f64, f64, f64) {
    match model {
        "claude-opus-5-5" => (4.0, 20.0, 5.0, 0.20),
        "claude-sonnet-5-5" => (2.0, 10.0, 2.5, 0.20),
        "claude-haiku-4-5" => (1.0, 5.0, 1.25, 0.10),
        // Historical ids (older claude_runs rows, fallback responses).
        "claude-sonnet-4-6" => (3.0, 15.0, 3.75, 0.30),
        _ => (5.0, 25.0, 6.25, 0.50),
    }
}

/// Models that accept `output_config.effort` and the server-side refusal
/// fallback. Haiku 4.5 rejects effort, so it gets neither.
fn is_current_gen(model: &str) -> bool {
    matches!(model, "claude-opus-5-5" | "claude-sonnet-5-5")
}

/// System prompt: kept compact and JSON-output-strict. Lives inline here
/// rather than in prompts/proposer-reviewer.md until we wire up the prompts
/// table — the on-disk version is the public-facing draft, this is what the
/// app actually sends. (~400 tokens: below the caching minimum, so uncached.)
pub const SYSTEM_PROMPT: &str = r#"You are reviewing a barre studio's monthly class schedule. The schedule was generated by a deterministic rule-based algorithm, then optionally edited by the lead teacher.

Your job: find SOFT improvements. Hard rules (qualifications, blocks, weekly caps) are already enforced — don't flag those. Focus especially on what the user's manual edits suggest.

For each suggestion, classify it:
- "add_rule": a rule the algorithm should permanently respect going forward (e.g., "Teacher E never on Reform" or "Teacher J never on Wednesday 5:45am")
- "tweak_parameter": an algorithm parameter to adjust (e.g., "increase variety penalty multiplier for Teacher G from 3.0 to 4.0")
- "fyi": an observation worth noting but no concrete change needed

Be conservative. If there are zero or one edits, suggest fewer things or none. Don't invent issues. If everything looks fine, say so in overall_assessment and return an empty suggestions array.

Output ONLY valid JSON in this exact shape — no preamble, no markdown fences, no commentary outside the JSON:

{
  "suggestions": [
    {
      "type": "add_rule" | "tweak_parameter" | "fyi",
      "summary": "one-line summary",
      "rationale": "why, with reference to specific edits or patterns",
      "confidence": "high" | "medium" | "low"
    }
  ],
  "overall_assessment": "one paragraph summary of the schedule and any patterns in the edits"
}"#;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ReviewSuggestion {
    #[serde(rename = "type")]
    pub kind: String,
    pub summary: String,
    pub rationale: String,
    pub confidence: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ReviewPayload {
    pub suggestions: Vec<ReviewSuggestion>,
    pub overall_assessment: String,
}

#[derive(Debug)]
pub struct ApiCall {
    pub payload: ReviewPayload,
    pub raw_input: String,
    pub model: String,
    pub input_tokens: u32,
    pub output_tokens: u32,
    // Cache-write tokens are priced into `cost_usd` (see compute_cost) but
    // not stored separately; the audit row only records cache reads.
    pub cache_read_input_tokens: u32,
    pub cost_usd: f64,
    pub duration_ms: u32,
}

#[derive(Deserialize)]
pub(crate) struct ApiResponse {
    pub(crate) content: Vec<ApiContentBlock>,
    pub(crate) model: String,
    #[serde(default)]
    pub(crate) stop_reason: Option<String>,
    pub(crate) usage: ApiUsage,
}

#[derive(Deserialize)]
pub(crate) struct ApiContentBlock {
    #[serde(rename = "type")]
    pub(crate) kind: String,
    #[serde(default)]
    pub(crate) text: String,
}

#[derive(Deserialize)]
pub(crate) struct ApiUsage {
    pub(crate) input_tokens: u32,
    pub(crate) output_tokens: u32,
    #[serde(default)]
    pub(crate) cache_creation_input_tokens: u32,
    #[serde(default)]
    pub(crate) cache_read_input_tokens: u32,
}

/// One system-prompt block; `cache` marks it with an ephemeral breakpoint
/// (only worth it when the prefix up to here exceeds the caching minimum).
pub(crate) struct SystemBlock<'a> {
    pub text: &'a str,
    pub cache: bool,
}

/// Per-call knobs.
pub(crate) struct CallOptions<'a> {
    pub max_tokens: u32,
    pub timeout: Duration,
    /// `output_config.effort` for models that support it.
    pub effort: &'a str,
}

/// One raw Anthropic Messages call: the shared plumbing under the review
/// and editor features.
pub(crate) struct RawCall {
    pub raw_input: String,
    pub raw_output: String,
    pub model: String,
    pub usage: ApiUsage,
    pub duration_ms: u32,
}

pub(crate) fn build_request_body(
    model: &str,
    system: &[SystemBlock<'_>],
    user_text: &str,
    opts: &CallOptions<'_>,
) -> Value {
    let system_json: Vec<Value> = system
        .iter()
        .map(|b| {
            if b.cache {
                json!({"type": "text", "text": b.text, "cache_control": {"type": "ephemeral"}})
            } else {
                json!({"type": "text", "text": b.text})
            }
        })
        .collect();
    let mut body = json!({
        "model": model,
        "max_tokens": opts.max_tokens,
        "system": system_json,
        "messages": [
            { "role": "user", "content": user_text }
        ]
    });
    if is_current_gen(model) {
        body["output_config"] = json!({ "effort": opts.effort });
        body["fallbacks"] = json!("default");
    }
    body
}

/// Map a non-success stop_reason to a clear error before anyone tries to
/// parse the (truncated or empty) text as JSON.
pub(crate) fn check_stop_reason(stop_reason: Option<&str>, max_tokens: u32) -> anyhow::Result<()> {
    match stop_reason {
        Some("max_tokens") => anyhow::bail!(
            "Claude's response was truncated (hit the {max_tokens}-token output limit) — \
             try a narrower instruction"
        ),
        Some("refusal") => anyhow::bail!("Claude declined this request"),
        _ => Ok(()),
    }
}

pub(crate) fn call_anthropic(
    api_key: &str,
    model: &str,
    system: &[SystemBlock<'_>],
    user_text: &str,
    opts: &CallOptions<'_>,
) -> anyhow::Result<RawCall> {
    let body = build_request_body(model, system, user_text, opts);

    let agent = ureq::Agent::config_builder()
        .http_status_as_error(false)
        .timeout_global(Some(opts.timeout))
        .build()
        .new_agent();
    let started = Instant::now();
    let mut req = agent
        .post(ANTHROPIC_URL)
        .header("x-api-key", api_key)
        .header("anthropic-version", ANTHROPIC_VERSION)
        .header("content-type", "application/json");
    if is_current_gen(model) {
        req = req.header("anthropic-beta", FALLBACK_BETA);
    }
    let resp = req.send_json(&body);
    let duration_ms = started.elapsed().as_millis() as u32;

    let mut resp = match resp {
        Ok(r) => r,
        Err(ureq::Error::Timeout(_)) => anyhow::bail!(
            "Anthropic API call timed out after {}s",
            opts.timeout.as_secs()
        ),
        Err(e) => anyhow::bail!("Anthropic API call failed: {e}"),
    };
    let status = resp.status().as_u16();
    if !(200..=299).contains(&status) {
        let body = resp.body_mut().read_to_string().unwrap_or_default();
        anyhow::bail!("Anthropic API returned HTTP {status}: {body}");
    }

    let api_response: ApiResponse = resp
        .body_mut()
        .read_json()
        .map_err(|e| anyhow::anyhow!("could not parse Anthropic response: {e}"))?;

    check_stop_reason(api_response.stop_reason.as_deref(), opts.max_tokens)?;

    // Only text blocks carry the answer; thinking/fallback blocks are skipped.
    let raw_output = api_response
        .content
        .iter()
        .filter(|b| b.kind == "text")
        .map(|b| b.text.as_str())
        .collect::<Vec<_>>()
        .join("");

    Ok(RawCall {
        raw_input: serde_json::to_string(&body).unwrap_or_default(),
        raw_output,
        model: api_response.model,
        usage: api_response.usage,
        duration_ms,
    })
}

/// Make one review call. `user_payload` is a JSON value the caller composed
/// (proposal + edits + roster). Returns the parsed suggestion structure plus
/// accounting fields for the audit log.
pub fn run_review(api_key: &str, model: &str, user_payload: &Value) -> anyhow::Result<ApiCall> {
    let user_text = format!(
        "Here is the proposal, the user's edits, and the roster as JSON. Review it per your instructions.\n\n{}",
        serde_json::to_string_pretty(user_payload)?
    );

    let call = call_anthropic(
        api_key,
        model,
        &[SystemBlock { text: SYSTEM_PROMPT, cache: false }],
        &user_text,
        &CallOptions { max_tokens: MAX_TOKENS, timeout: REVIEW_TIMEOUT, effort: "medium" },
    )?;

    let payload: ReviewPayload = serde_json::from_str(extract_json(&call.raw_output))
        .map_err(|e| {
            anyhow::anyhow!(
                "Claude did not return valid JSON in the expected shape: {e}\n---\n{}",
                call.raw_output
            )
        })?;

    let cost_usd = compute_cost(&call.model, &call.usage);

    Ok(ApiCall {
        payload,
        raw_input: call.raw_input,
        input_tokens: call.usage.input_tokens,
        output_tokens: call.usage.output_tokens,
        cache_read_input_tokens: call.usage.cache_read_input_tokens,
        model: call.model,
        cost_usd,
        duration_ms: call.duration_ms,
    })
}

pub(crate) fn compute_cost(model: &str, u: &ApiUsage) -> f64 {
    let (input, output, cache_write, cache_read) = model_prices(model);
    let m = 1_000_000.0;
    (u.input_tokens as f64 * input
        + u.cache_creation_input_tokens as f64 * cache_write
        + u.cache_read_input_tokens as f64 * cache_read
        + u.output_tokens as f64 * output)
        / m
}

/// If Claude wraps the JSON in ```json ... ``` despite our instructions,
/// peel that off. Otherwise return as-is.
pub(crate) fn extract_json(text: &str) -> &str {
    let trimmed = text.trim();
    if let Some(rest) = trimmed.strip_prefix("```json") {
        return rest.trim().trim_end_matches("```").trim();
    }
    if let Some(rest) = trimmed.strip_prefix("```") {
        return rest.trim().trim_end_matches("```").trim();
    }
    trimmed
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn model_prices_known_and_fallback() {
        assert_eq!(model_prices("claude-opus-5-5").0, 4.0);
        assert_eq!(model_prices("claude-sonnet-5-5").1, 10.0);
        assert_eq!(model_prices("claude-haiku-4-5").1, 5.0);
        // Unknown ids price at the (higher) older-Opus rate.
        assert_eq!(model_prices("claude-9000").0, 5.0);
    }

    #[test]
    fn cost_uses_the_models_prices() {
        let usage = ApiUsage {
            input_tokens: 1_000_000,
            output_tokens: 0,
            cache_creation_input_tokens: 0,
            cache_read_input_tokens: 0,
        };
        assert!((compute_cost("claude-haiku-4-5", &usage) - 1.0).abs() < 1e-9);
        assert!((compute_cost("claude-opus-5-5", &usage) - 4.0).abs() < 1e-9);
    }

    #[test]
    fn request_body_per_model() {
        let opts = CallOptions { max_tokens: 100, timeout: Duration::from_secs(1), effort: "high" };
        let blocks = [
            SystemBlock { text: "instructions", cache: false },
            SystemBlock { text: "big script", cache: true },
        ];
        let b = build_request_body("claude-opus-5-5", &blocks, "hi", &opts);
        assert_eq!(b["output_config"]["effort"], "high");
        assert_eq!(b["fallbacks"], "default");
        assert!(b["system"][0].get("cache_control").is_none());
        assert_eq!(b["system"][1]["cache_control"]["type"], "ephemeral");
        assert!(b.get("thinking").is_none(), "5.5 models think adaptively by default");

        // Haiku 4.5 rejects effort; no fallback either.
        let h = build_request_body("claude-haiku-4-5", &blocks, "hi", &opts);
        assert!(h.get("output_config").is_none());
        assert!(h.get("fallbacks").is_none());
    }

    #[test]
    fn stop_reason_errors_are_clear() {
        assert!(check_stop_reason(Some("end_turn"), 10).is_ok());
        assert!(check_stop_reason(None, 10).is_ok());
        let e = check_stop_reason(Some("max_tokens"), 16000).unwrap_err().to_string();
        assert!(e.contains("truncated") && e.contains("16000"), "{e}");
        let e = check_stop_reason(Some("refusal"), 10).unwrap_err().to_string();
        assert!(e.contains("declined"), "{e}");
    }
}
