// Anthropic API integration for the schedule-review feature.
// Sync HTTP via ureq — Tauri runs commands on a worker thread, so a blocking
// call doesn't freeze the UI.
//
// The system prompt is sent with cache_control: ephemeral so subsequent
// reviews within ~5 minutes hit the cache and pay 10% of input price.

use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

const ANTHROPIC_URL: &str = "https://api.anthropic.com/v1/messages";
const ANTHROPIC_VERSION: &str = "2023-06-01";

const MAX_TOKENS: u32 = 4096;

/// List pricing per model (USD per 1M tokens): (input, output, cache_write,
/// cache_read). Cache-write is +25%, cache-read is -90% of input. Unknown
/// models price as Opus 4.8 (the default) so costs are never understated.
pub fn model_prices(model: &str) -> (f64, f64, f64, f64) {
    match model {
        "claude-sonnet-4-6" => (3.0, 15.0, 3.75, 0.30),
        "claude-haiku-4-5" => (1.0, 5.0, 1.25, 0.10),
        _ => (5.0, 25.0, 6.25, 0.50), // claude-opus-4-8 + fallback
    }
}

/// System prompt: kept compact and JSON-output-strict. Lives inline here
/// rather than in prompts/proposer-reviewer.md until we wire up the prompts
/// table — the on-disk version is the public-facing draft, this is what the
/// app actually sends.
pub const SYSTEM_PROMPT: &str = r#"You are reviewing a the barre studio studio's monthly class schedule. The schedule was generated by a deterministic rule-based algorithm (v9), then optionally edited by the lead teacher.

Your job: find SOFT improvements. Hard rules (qualifications, blocks, weekly caps) are already enforced — don't flag those. Focus especially on what the user's manual edits suggest.

For each suggestion, classify it:
- "add_rule": a rule the algorithm should permanently respect going forward (e.g., "Teacher E never on Reform" or "Teacher J never on Wednesday 5:45am")
- "tweak_parameter": an algorithm parameter to adjust (e.g., "increase variety penalty multiplier for Teacher G from 3.0 to 4.0")
- "fyi": an observation worth noting but no concrete change needed

Be conservative. If there are zero or one edits, suggest fewer things or none. Don't invent issues. If everything looks fine, say so in overall_assessment and return an empty suggestions array.

Output ONLY valid JSON in this exact shape — no preamble, no markdown fences, no commentary outside the JSON:

{
  "suggestions": [
    {
      "type": "add_rule" | "tweak_parameter" | "fyi",
      "summary": "one-line summary",
      "rationale": "why, with reference to specific edits or patterns",
      "confidence": "high" | "medium" | "low"
    }
  ],
  "overall_assessment": "one paragraph summary of the schedule and any patterns in the edits"
}"#;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ReviewSuggestion {
    #[serde(rename = "type")]
    pub kind: String,
    pub summary: String,
    pub rationale: String,
    pub confidence: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ReviewPayload {
    pub suggestions: Vec<ReviewSuggestion>,
    pub overall_assessment: String,
}

#[derive(Debug)]
pub struct ApiCall {
    pub payload: ReviewPayload,
    pub raw_input: String,
    pub raw_output: String,
    pub model: String,
    pub input_tokens: u32,
    pub output_tokens: u32,
    pub cache_creation_input_tokens: u32,
    pub cache_read_input_tokens: u32,
    pub cost_usd: f64,
    pub duration_ms: u32,
}

#[derive(Deserialize)]
pub(crate) struct ApiResponse {
    pub(crate) content: Vec<ApiContentBlock>,
    pub(crate) model: String,
    pub(crate) usage: ApiUsage,
}

#[derive(Deserialize)]
pub(crate) struct ApiContentBlock {
    #[serde(rename = "type")]
    pub(crate) kind: String,
    #[serde(default)]
    pub(crate) text: String,
}

#[derive(Deserialize)]
pub(crate) struct ApiUsage {
    pub(crate) input_tokens: u32,
    pub(crate) output_tokens: u32,
    #[serde(default)]
    pub(crate) cache_creation_input_tokens: u32,
    #[serde(default)]
    pub(crate) cache_read_input_tokens: u32,
}

/// One raw Anthropic Messages call: the shared plumbing under the review
/// and editor features. The system prompt is cached (ephemeral) so repeat
/// interactions within ~5 minutes pay 10% of input price.
pub(crate) struct RawCall {
    pub raw_input: String,
    pub raw_output: String,
    pub model: String,
    pub usage: ApiUsage,
    pub duration_ms: u32,
}

pub(crate) fn call_anthropic(
    api_key: &str,
    model: &str,
    system: &str,
    user_text: &str,
    max_tokens: u32,
) -> anyhow::Result<RawCall> {
    let body = json!({
        "model": model,
        "max_tokens": max_tokens,
        "system": [
            {
                "type": "text",
                "text": system,
                "cache_control": { "type": "ephemeral" }
            }
        ],
        "messages": [
            { "role": "user", "content": user_text }
        ]
    });

    let started = Instant::now();
    let resp = ureq::post(ANTHROPIC_URL)
        .set("x-api-key", api_key)
        .set("anthropic-version", ANTHROPIC_VERSION)
        .set("content-type", "application/json")
        .timeout(Duration::from_secs(120))
        .send_json(&body);
    let duration_ms = started.elapsed().as_millis() as u32;

    let resp = match resp {
        Ok(r) => r,
        Err(ureq::Error::Status(code, r)) => {
            let body = r.into_string().unwrap_or_default();
            anyhow::bail!("Anthropic API returned HTTP {code}: {body}");
        }
        Err(e) => anyhow::bail!("Anthropic API call failed: {e}"),
    };

    let api_response: ApiResponse = resp
        .into_json()
        .map_err(|e| anyhow::anyhow!("could not parse Anthropic response: {e}"))?;

    let raw_output = api_response
        .content
        .iter()
        .filter(|b| b.kind == "text")
        .map(|b| b.text.as_str())
        .collect::<Vec<_>>()
        .join("");

    Ok(RawCall {
        raw_input: serde_json::to_string(&body).unwrap_or_default(),
        raw_output,
        model: api_response.model,
        usage: api_response.usage,
        duration_ms,
    })
}

/// Make one review call. `user_payload` is a JSON value the caller composed
/// (proposal + edits + roster). Returns the parsed suggestion structure plus
/// accounting fields for the audit log.
pub fn run_review(api_key: &str, model: &str, user_payload: &Value) -> anyhow::Result<ApiCall> {
    let user_text = format!(
        "Here is the proposal, the user's edits, and the roster as JSON. Review it per your instructions.\n\n{}",
        serde_json::to_string_pretty(user_payload)?
    );

    let call = call_anthropic(api_key, model, SYSTEM_PROMPT, &user_text, MAX_TOKENS)?;

    let payload: ReviewPayload = serde_json::from_str(extract_json(&call.raw_output))
        .map_err(|e| {
            anyhow::anyhow!(
                "Claude did not return valid JSON in the expected shape: {e}\n---\n{}",
                call.raw_output
            )
        })?;

    let cost_usd = compute_cost(&call.model, &call.usage);

    Ok(ApiCall {
        payload,
        raw_input: call.raw_input,
        raw_output: call.raw_output,
        input_tokens: call.usage.input_tokens,
        output_tokens: call.usage.output_tokens,
        cache_creation_input_tokens: call.usage.cache_creation_input_tokens,
        cache_read_input_tokens: call.usage.cache_read_input_tokens,
        model: call.model,
        cost_usd,
        duration_ms: call.duration_ms,
    })
}

pub(crate) fn compute_cost(model: &str, u: &ApiUsage) -> f64 {
    let (input, output, cache_write, cache_read) = model_prices(model);
    let m = 1_000_000.0;
    (u.input_tokens as f64 * input
        + u.cache_creation_input_tokens as f64 * cache_write
        + u.cache_read_input_tokens as f64 * cache_read
        + u.output_tokens as f64 * output)
        / m
}

/// If Claude wraps the JSON in ```json ... ``` despite our instructions,
/// peel that off. Otherwise return as-is.
pub(crate) fn extract_json(text: &str) -> &str {
    let trimmed = text.trim();
    if let Some(rest) = trimmed.strip_prefix("```json") {
        return rest.trim().trim_end_matches("```").trim();
    }
    if let Some(rest) = trimmed.strip_prefix("```") {
        return rest.trim().trim_end_matches("```").trim();
    }
    trimmed
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn model_prices_known_and_fallback() {
        assert_eq!(model_prices("claude-sonnet-4-6").0, 3.0);
        assert_eq!(model_prices("claude-haiku-4-5").1, 5.0);
        // Default and unknown both price as Opus.
        assert_eq!(model_prices("claude-opus-4-8"), model_prices("claude-9000"));
    }

    #[test]
    fn cost_uses_the_models_prices() {
        let usage = ApiUsage {
            input_tokens: 1_000_000,
            output_tokens: 0,
            cache_creation_input_tokens: 0,
            cache_read_input_tokens: 0,
        };
        assert!((compute_cost("claude-haiku-4-5", &usage) - 1.0).abs() < 1e-9);
        assert!((compute_cost("claude-opus-4-8", &usage) - 5.0).abs() < 1e-9);
    }
}
