// Anthropic API integration for the schedule-review feature.
// Sync HTTP via ureq — Tauri runs commands on a worker thread, so a blocking
// call doesn't freeze the UI.
//
// The system prompt is sent with cache_control: ephemeral so subsequent
// reviews within ~5 minutes hit the cache and pay 10% of input price.

use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

const ANTHROPIC_URL: &str = "https://api.anthropic.com/v1/messages";
const ANTHROPIC_VERSION: &str = "2023-06-01";

/// Sonnet 4.6 — good quality, fast, cheap. Right tradeoff for schedule
/// review (the input is structured, the task is bounded).
pub const REVIEW_MODEL: &str = "claude-sonnet-4-6";
const MAX_TOKENS: u32 = 4096;

// Sonnet 4.6 list pricing (USD per 1M tokens). Cache-write is +25%,
// cache-read is -90%. We compute cost from the usage object the API returns.
const PRICE_INPUT_PER_MTOK: f64 = 3.0;
const PRICE_OUTPUT_PER_MTOK: f64 = 15.0;
const PRICE_CACHE_WRITE_PER_MTOK: f64 = 3.75;
const PRICE_CACHE_READ_PER_MTOK: f64 = 0.30;

/// System prompt: kept compact and JSON-output-strict. Lives inline here
/// rather than in prompts/proposer-reviewer.md until we wire up the prompts
/// table — the on-disk version is the public-facing draft, this is what the
/// app actually sends.
pub const SYSTEM_PROMPT: &str = r#"You are reviewing a the barre studio studio's monthly class schedule. The schedule was generated by a deterministic rule-based algorithm (v9), then optionally edited by the lead teacher.

Your job: find SOFT improvements. Hard rules (qualifications, blocks, weekly caps) are already enforced — don't flag those. Focus especially on what the user's manual edits suggest.

For each suggestion, classify it:
- "add_rule": a rule the algorithm should permanently respect going forward (e.g., "Teacher E never on Reform" or "Teacher J never on Wednesday 5:45am")
- "tweak_parameter": an algorithm parameter to adjust (e.g., "increase variety penalty multiplier for Teacher G from 3.0 to 4.0")
- "fyi": an observation worth noting but no concrete change needed

Be conservative. If there are zero or one edits, suggest fewer things or none. Don't invent issues. If everything looks fine, say so in overall_assessment and return an empty suggestions array.

Output ONLY valid JSON in this exact shape — no preamble, no markdown fences, no commentary outside the JSON:

{
  "suggestions": [
    {
      "type": "add_rule" | "tweak_parameter" | "fyi",
      "summary": "one-line summary",
      "rationale": "why, with reference to specific edits or patterns",
      "confidence": "high" | "medium" | "low"
    }
  ],
  "overall_assessment": "one paragraph summary of the schedule and any patterns in the edits"
}"#;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ReviewSuggestion {
    #[serde(rename = "type")]
    pub kind: String,
    pub summary: String,
    pub rationale: String,
    pub confidence: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ReviewPayload {
    pub suggestions: Vec<ReviewSuggestion>,
    pub overall_assessment: String,
}

#[derive(Debug)]
pub struct ApiCall {
    pub payload: ReviewPayload,
    pub raw_input: String,
    pub raw_output: String,
    pub model: String,
    pub input_tokens: u32,
    pub output_tokens: u32,
    pub cache_creation_input_tokens: u32,
    pub cache_read_input_tokens: u32,
    pub cost_usd: f64,
    pub duration_ms: u32,
}

#[derive(Deserialize)]
struct ApiResponse {
    content: Vec<ApiContentBlock>,
    model: String,
    usage: ApiUsage,
}

#[derive(Deserialize)]
struct ApiContentBlock {
    #[serde(rename = "type")]
    kind: String,
    #[serde(default)]
    text: String,
}

#[derive(Deserialize)]
struct ApiUsage {
    input_tokens: u32,
    output_tokens: u32,
    #[serde(default)]
    cache_creation_input_tokens: u32,
    #[serde(default)]
    cache_read_input_tokens: u32,
}

/// Make one Anthropic Messages call. `user_payload` is a JSON value the
/// frontend caller composed (proposal + edits + roster). Returns the parsed
/// suggestion structure plus accounting fields for the audit log.
pub fn run_review(api_key: &str, user_payload: &Value) -> anyhow::Result<ApiCall> {
    let user_text = format!(
        "Here is the proposal, the user's edits, and the roster as JSON. Review it per your instructions.\n\n{}",
        serde_json::to_string_pretty(user_payload)?
    );

    let body = json!({
        "model": REVIEW_MODEL,
        "max_tokens": MAX_TOKENS,
        "system": [
            {
                "type": "text",
                "text": SYSTEM_PROMPT,
                "cache_control": { "type": "ephemeral" }
            }
        ],
        "messages": [
            { "role": "user", "content": user_text }
        ]
    });

    let agent = ureq::Agent::config_builder()
        .http_status_as_error(false)
        .timeout_global(Some(Duration::from_secs(120)))
        .build()
        .new_agent();
    let started = Instant::now();
    let resp = agent
        .post(ANTHROPIC_URL)
        .header("x-api-key", api_key)
        .header("anthropic-version", ANTHROPIC_VERSION)
        .header("content-type", "application/json")
        .send_json(&body);
    let duration_ms = started.elapsed().as_millis() as u32;

    let mut resp = match resp {
        Ok(r) => r,
        Err(e) => anyhow::bail!("Anthropic API call failed: {e}"),
    };
    let status = resp.status().as_u16();
    if !(200..=299).contains(&status) {
        let body = resp.body_mut().read_to_string().unwrap_or_default();
        anyhow::bail!("Anthropic API returned HTTP {status}: {body}");
    }

    let api_response: ApiResponse = resp
        .body_mut()
        .read_json()
        .map_err(|e| anyhow::anyhow!("could not parse Anthropic response: {e}"))?;

    let raw_output = api_response
        .content
        .iter()
        .filter(|b| b.kind == "text")
        .map(|b| b.text.as_str())
        .collect::<Vec<_>>()
        .join("");

    let payload: ReviewPayload = serde_json::from_str(extract_json(&raw_output))
        .map_err(|e| {
            anyhow::anyhow!(
                "Claude did not return valid JSON in the expected shape: {e}\n---\n{raw_output}"
            )
        })?;

    let cost_usd = compute_cost(&api_response.usage);

    Ok(ApiCall {
        payload,
        raw_input: serde_json::to_string(&body).unwrap_or_default(),
        raw_output,
        model: api_response.model,
        input_tokens: api_response.usage.input_tokens,
        output_tokens: api_response.usage.output_tokens,
        cache_creation_input_tokens: api_response.usage.cache_creation_input_tokens,
        cache_read_input_tokens: api_response.usage.cache_read_input_tokens,
        cost_usd,
        duration_ms,
    })
}

fn compute_cost(u: &ApiUsage) -> f64 {
    let m = 1_000_000.0;
    (u.input_tokens as f64 * PRICE_INPUT_PER_MTOK
        + u.cache_creation_input_tokens as f64 * PRICE_CACHE_WRITE_PER_MTOK
        + u.cache_read_input_tokens as f64 * PRICE_CACHE_READ_PER_MTOK
        + u.output_tokens as f64 * PRICE_OUTPUT_PER_MTOK)
        / m
}

/// If Claude wraps the JSON in ```json ... ``` despite our instructions,
/// peel that off. Otherwise return as-is.
fn extract_json(text: &str) -> &str {
    let trimmed = text.trim();
    if let Some(rest) = trimmed.strip_prefix("```json") {
        return rest.trim().trim_end_matches("```").trim();
    }
    if let Some(rest) = trimmed.strip_prefix("```") {
        return rest.trim().trim_end_matches("```").trim();
    }
    trimmed
}
